package rest.mybatis.model.eBillModel;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.databind.ser.Serializers;
/**
 * @TODO 文件路径
 * @author 刘宗峰
 *
 */
public class FileAddress implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_ADDRESS.id
     * 主键
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_ADDRESS.FILE_PATH
     * 路径
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_ADDRESS.COM_NUM
     * 工号
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    private String comNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_ADDRESS.ISSUE_ID
     * 当前期数id
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    private String issueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_ADDRESS.OPERATE_DATE
     * 操作时间
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    private Date operateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_ADDRESS.IS_LIVE
     * 是否有效
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    private Integer isLive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_ADDRESS.id
     *
     * @return the value of FILE_ADDRESS.id
     *
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_ADDRESS.id
     *
     * @param id the value for FILE_ADDRESS.id
     *
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_ADDRESS.FILE_PATH
     *
     * @return the value of FILE_ADDRESS.FILE_PATH
     *
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_ADDRESS.FILE_PATH
     *
     * @param filePath the value for FILE_ADDRESS.FILE_PATH
     *
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_ADDRESS.COM_NUM
     *
     * @return the value of FILE_ADDRESS.COM_NUM
     *
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    public String getComNum() {
        return comNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_ADDRESS.COM_NUM
     *
     * @param comNum the value for FILE_ADDRESS.COM_NUM
     *
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    public void setComNum(String comNum) {
        this.comNum = comNum == null ? null : comNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_ADDRESS.ISSUE_ID
     *
     * @return the value of FILE_ADDRESS.ISSUE_ID
     *
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    public String getIssueId() {
        return issueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_ADDRESS.ISSUE_ID
     *
     * @param issueId the value for FILE_ADDRESS.ISSUE_ID
     *
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    public void setIssueId(String issueId) {
        this.issueId = issueId == null ? null : issueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_ADDRESS.OPERATE_DATE
     *
     * @return the value of FILE_ADDRESS.OPERATE_DATE
     *
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    public Date getOperateDate() {
        return operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_ADDRESS.OPERATE_DATE
     *
     * @param operateDate the value for FILE_ADDRESS.OPERATE_DATE
     *
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    public void setOperateDate(Date operateDate) {
        this.operateDate = operateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_ADDRESS.IS_LIVE
     *
     * @return the value of FILE_ADDRESS.IS_LIVE
     *
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    public Integer getIsLive() {
        return isLive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_ADDRESS.IS_LIVE
     *
     * @param isLive the value for FILE_ADDRESS.IS_LIVE
     *
     * @mbggenerated Tue Jan 23 14:05:11 CST 2018
     */
    public void setIsLive(Integer isLive) {
        this.isLive = isLive;
    }
}